### ISSUE TITLE
Library Inclusion - D3

### ISSUE THREAD

**Issue by AlcorSalvador** [OlegWock/obsidian-emera#2]
Pretty Large sitting at 5mb, but it has a wide range of functionality for Graph Generation and Data Visualization.
Maybe an insane request but I believe it is both useful enough to add and popular enough to warrant it.

**Comment by OlegWock** [comment]
5mb is just too much, sorry! Emera is already takes quite a bit of time on Obsidian initialization, most of which is spent parsing the JS code. Adding 5 more mb to it will increase time to initialize significantly

But you can fork this plugin and include D3 in your fork. You just need to install it and add it to [exposed-modules.ts](https://github.com/OlegWock/obsidian-emera/blob/master/src/exposed-modules.ts). And then compile the extension with `yarn build` or `npm run build`

**Comment by AlcorSalvador** [comment]
Fair Enough o7
